// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhKCGn50hZ_oQ3sSyn9zyLICQRlurQ9C8',
    appId: '1:697451256167:web:e74aacc8e1f99a6bc0b7c2',
    messagingSenderId: '697451256167',
    projectId: 'cash-app-86b0b',
    authDomain: 'cash-app-86b0b.firebaseapp.com',
    storageBucket: 'cash-app-86b0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABuzDuoa8MqLR9PI6EfCPGmtuiYZ8FFgM',
    appId: '1:697451256167:android:c443c8e3c2ad7aa2c0b7c2',
    messagingSenderId: '697451256167',
    projectId: 'cash-app-86b0b',
    storageBucket: 'cash-app-86b0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgDvOZEVyZGv8PT5ppRupfAHDzilLoeCk',
    appId: '1:697451256167:ios:8dc18d18b8cecc6ac0b7c2',
    messagingSenderId: '697451256167',
    projectId: 'cash-app-86b0b',
    storageBucket: 'cash-app-86b0b.appspot.com',
    iosBundleId: 'com.example.cashApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgDvOZEVyZGv8PT5ppRupfAHDzilLoeCk',
    appId: '1:697451256167:ios:8dc18d18b8cecc6ac0b7c2',
    messagingSenderId: '697451256167',
    projectId: 'cash-app-86b0b',
    storageBucket: 'cash-app-86b0b.appspot.com',
    iosBundleId: 'com.example.cashApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhKCGn50hZ_oQ3sSyn9zyLICQRlurQ9C8',
    appId: '1:697451256167:web:b3532de80bc88f2dc0b7c2',
    messagingSenderId: '697451256167',
    projectId: 'cash-app-86b0b',
    authDomain: 'cash-app-86b0b.firebaseapp.com',
    storageBucket: 'cash-app-86b0b.appspot.com',
  );
}
